name: Deploy to Server

on:
  push:
    branches:
      - stage
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.109.208.39 >> ~/.ssh/known_hosts
          ssh-keyscan 3.109.208.135 >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Install Dependencies and Build
        run: |
          export CI=false
          npm install --force
          npm run build

      - name: Deploy Build to Server
        run: |
          if [ $GITHUB_REF = 'refs/heads/stage' ]; then
            scp -r ./build/* ubuntu@3.109.208.39:/home/ubuntu/s1projects
          elif [ $GITHUB_REF = 'refs/heads/production' ]; then
            scp -r ./build/* ubuntu@3.109.208.135:/home/ubuntu/s2projects
          fi





